-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT fk_categories_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  phone text,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  tipo_documento text CHECK (tipo_documento IS NULL OR (tipo_documento = ANY (ARRAY['CC'::text, 'NIT'::text, 'CE'::text, 'PAS'::text, 'TI'::text, 'RC'::text, 'DE'::text]))),
  numero_documento text,
  documento_dv text,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT fk_clients_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact text,
  phone text,
  email text,
  address text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  tipo_documento text CHECK (tipo_documento IS NULL OR (tipo_documento = ANY (ARRAY['CC'::text, 'NIT'::text, 'CE'::text, 'PAS'::text, 'TI'::text, 'RC'::text, 'DE'::text]))),
  numero_documento text,
  documento_dv text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_suppliers_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  barcode text,
  category_id uuid,
  supplier_id uuid,
  sale_price numeric NOT NULL,
  min_stock integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  image_url text,
  company_id uuid NOT NULL,
  is_public boolean DEFAULT true,
  requiere_receta boolean NOT NULL DEFAULT false,
  es_controlado boolean NOT NULL DEFAULT false,
  principio_activo text,
  concentracion text,
  forma_farmaceutica text,
  registro_invima text,
  unidad_medida text NOT NULL DEFAULT 'unidad'::text,
  tipo_tributo_iva text NOT NULL DEFAULT 'excluido'::text CHECK (tipo_tributo_iva = ANY (ARRAY['excluido'::text, 'exento'::text, 'gravado_5'::text, 'gravado_19'::text])),
  codigo_cum text,
  clasificacion_atc text,
  via_administracion text,
  laboratorio_titular text,
  vigencia_registro_sanitario date,
  requiere_cadena_frio boolean NOT NULL DEFAULT false,
  permite_venta_fraccionada boolean NOT NULL DEFAULT false,
  unidades_por_presentacion integer NOT NULL DEFAULT 1 CHECK (unidades_por_presentacion > 0),
  es_generico boolean NOT NULL DEFAULT false,
  producto_referencia_id uuid,
  comision_porcentaje numeric NOT NULL DEFAULT 0 CHECK (comision_porcentaje >= 0::numeric AND comision_porcentaje <= 100::numeric),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT fk_products_company FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT products_referencia_fkey FOREIGN KEY (producto_referencia_id) REFERENCES public.products(id)
);
CREATE TABLE public.purchase_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  quantity integer NOT NULL,
  purchase_price numeric NOT NULL,
  purchase_date timestamp with time zone DEFAULT now(),
  remaining_quantity integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  supplier_id uuid,
  company_id uuid NOT NULL,
  fecha_vencimiento date,
  numero_lote_fabricante text,
  CONSTRAINT purchase_batches_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_batches_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT purchase_batches_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT fk_batches_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  description text NOT NULL,
  amount numeric NOT NULL,
  category bigint,
  date timestamp with time zone DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  forma_pago text NOT NULL DEFAULT 'efectivo'::text CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'banco'::text])),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fk_expenses_company FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT expenses_category_fkey FOREIGN KEY (category) REFERENCES public.categories_expense(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  total numeric NOT NULL,
  payment_method text NOT NULL,
  sale_date timestamp with time zone DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  is_credit boolean NOT NULL DEFAULT false,
  venta_uid uuid,
  turno_caja_id uuid,
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT sales_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fk_sales_company FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT sales_turno_caja_id_fkey FOREIGN KEY (turno_caja_id) REFERENCES public.turnos_caja(id)
);
CREATE TABLE public.sale_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  product_id uuid NOT NULL,
  batch_id uuid NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  subtotal numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  CONSTRAINT sale_items_pkey PRIMARY KEY (id),
  CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT sale_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT sale_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.purchase_batches(id),
  CONSTRAINT fk_saleitems_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.sales_profit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL UNIQUE,
  total_cost numeric NOT NULL,
  total_sale numeric NOT NULL,
  profit numeric NOT NULL,
  profit_margin numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  CONSTRAINT sales_profit_pkey PRIMARY KEY (id),
  CONSTRAINT sales_profit_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT fk_salesprofit_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['entrada'::text, 'salida'::text, 'ajuste'::text])),
  quantity integer NOT NULL,
  reason text,
  date timestamp with time zone DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT fk_inventory_company FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.user_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'vendedor'::text, 'gerente'::text])),
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  domain text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  phone text,
  logo_url text,
  theme jsonb DEFAULT '{"accent": "oklch(0.88 0.12 85)", "radius": "0.75rem", "primary": "oklch(0.60 0.18 320)", "secondary": "oklch(0.92 0.04 340)", "darkPrimary": "oklch(0.70 0.18 330)"}'::jsonb,
  catalog_stock text,
  plantilla_cobro text,
  tipo_negocio text NOT NULL DEFAULT 'general'::text CHECK (tipo_negocio = ANY (ARRAY['general'::text, 'cosmeticos'::text, 'drogueria'::text, 'comida_rapida'::text])),
  nit text,
  nit_dv text,
  razon_social text,
  direccion_fiscal text,
  actividad_economica_ciiu text,
  regimen_tributario text CHECK (regimen_tributario IS NULL OR (regimen_tributario = ANY (ARRAY['responsable_iva'::text, 'no_responsable_iva'::text]))),
  director_tecnico_nombre text,
  director_tecnico_documento text,
  director_tecnico_tarjeta_profesional text,
  numero_licencia_funcionamiento text,
  entidad_territorial_salud text,
  vigencia_licencia_funcionamiento date,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'gerente'::text, 'vendedor'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_companies_pkey PRIMARY KEY (id),
  CONSTRAINT user_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.customer_debts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  sale_id uuid NOT NULL,
  client_id uuid NOT NULL,
  original_amount numeric NOT NULL CHECK (original_amount > 0::numeric),
  paid_amount numeric NOT NULL DEFAULT 0 CHECK (paid_amount >= 0::numeric),
  remaining_amount numeric DEFAULT (original_amount - paid_amount),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'cancelled'::text])),
  notes text,
  due_date date,
  paid_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_debts_pkey PRIMARY KEY (id),
  CONSTRAINT customer_debts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT customer_debts_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id),
  CONSTRAINT customer_debts_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT customer_debts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.debt_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  debt_id uuid NOT NULL,
  company_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  forma_pago text NOT NULL DEFAULT 'efectivo'::text CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'banco'::text])),
  CONSTRAINT debt_payments_pkey PRIMARY KEY (id),
  CONSTRAINT debt_payments_debt_id_fkey FOREIGN KEY (debt_id) REFERENCES public.customer_debts(id),
  CONSTRAINT debt_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.categories_expense (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name character varying,
  company_id uuid NOT NULL,
  CONSTRAINT categories_expense_pkey PRIMARY KEY (id),
  CONSTRAINT categories_expense_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.product_kits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  code integer NOT NULL CHECK (code > 0),
  name text NOT NULL CHECK (char_length(TRIM(BOTH FROM name)) >= 2),
  description text,
  image_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_catalog_order boolean NOT NULL DEFAULT false,
  catalog_status text,
  client_name text,
  client_phone text,
  expires_at timestamp with time zone,
  reclaimed_at timestamp with time zone,
  sale_id uuid,
  frozen_total numeric,
  campania_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  cancellation_reason text,
  CONSTRAINT product_kits_pkey PRIMARY KEY (id),
  CONSTRAINT product_kits_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT product_kits_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT product_kits_sale_fk FOREIGN KEY (sale_id) REFERENCES public.sales(id)
);
CREATE TABLE public.product_kit_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kit_id uuid NOT NULL,
  company_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price_in_kit numeric NOT NULL CHECK (unit_price_in_kit >= 0::numeric),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_kit_items_pkey PRIMARY KEY (id),
  CONSTRAINT kit_items_product_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT kit_items_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT kit_items_kit_fkey FOREIGN KEY (kit_id) REFERENCES public.product_kits(id)
);
CREATE TABLE public.campanias_descuento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  nombre text NOT NULL CHECK (char_length(TRIM(BOTH FROM nombre)) >= 2),
  descripcion text,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  margen_minimo numeric NOT NULL CHECK (margen_minimo >= 0::numeric AND margen_minimo < 100::numeric),
  estado text NOT NULL DEFAULT 'BORRADOR'::text CHECK (estado = ANY (ARRAY['BORRADOR'::text, 'CALCULADA'::text, 'APROBADA'::text, 'PUBLICADA'::text, 'CANCELADA'::text])),
  criterio_seleccion jsonb NOT NULL DEFAULT '{"modo": "TODOS"}'::jsonb CHECK ((criterio_seleccion ->> 'modo'::text) = ANY (ARRAY['TODOS'::text, 'SIN_ROTACION'::text, 'SOBRESTOCK'::text, 'CATEGORIA'::text, 'PROVEEDOR'::text, 'MANUAL'::text])),
  aprobado_at timestamp with time zone,
  publicado_at timestamp with time zone,
  cancelado_at timestamp with time zone,
  motivo_cancelacion text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT campanias_descuento_pkey PRIMARY KEY (id),
  CONSTRAINT campanias_descuento_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT campanias_descuento_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.campania_descuento_detalle (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campania_id uuid NOT NULL,
  company_id uuid NOT NULL,
  product_id uuid NOT NULL,
  lote_id uuid NOT NULL,
  cantidad_disponible integer NOT NULL,
  precio_compra numeric NOT NULL,
  precio_venta_actual numeric NOT NULL,
  porcentaje_maximo_permitido numeric NOT NULL DEFAULT 0 CHECK (porcentaje_maximo_permitido >= 0::numeric AND porcentaje_maximo_permitido <= 100::numeric),
  precio_minimo_permitido numeric NOT NULL DEFAULT 0,
  porcentaje_descuento_aprobado numeric NOT NULL DEFAULT 0 CHECK (porcentaje_descuento_aprobado >= 0::numeric AND porcentaje_descuento_aprobado <= 100::numeric),
  precio_oferta numeric,
  margen_resultante numeric,
  ganancia_por_unidad numeric,
  ganancia_total_estimada numeric,
  activo boolean NOT NULL DEFAULT true,
  motivo_inactivo text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campania_descuento_detalle_pkey PRIMARY KEY (id),
  CONSTRAINT campania_descuento_detalle_campania_id_fkey FOREIGN KEY (campania_id) REFERENCES public.campanias_descuento(id),
  CONSTRAINT campania_descuento_detalle_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT campania_descuento_detalle_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT campania_descuento_detalle_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.purchase_batches(id)
);
CREATE TABLE public.ofertas_virtuales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  campania_id uuid NOT NULL,
  product_id uuid NOT NULL,
  lote_id uuid,
  precio_original numeric NOT NULL,
  precio_oferta numeric NOT NULL,
  porcentaje_descuento numeric NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  desactivado_at timestamp with time zone,
  CONSTRAINT ofertas_virtuales_pkey PRIMARY KEY (id),
  CONSTRAINT ofertas_virtuales_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT ofertas_virtuales_campania_id_fkey FOREIGN KEY (campania_id) REFERENCES public.campanias_descuento(id),
  CONSTRAINT ofertas_virtuales_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT ofertas_virtuales_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.purchase_batches(id)
);
CREATE TABLE public.cierres_mensuales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  anio integer NOT NULL,
  mes integer NOT NULL CHECK (mes >= 1 AND mes <= 12),
  saldo_inicial numeric NOT NULL DEFAULT 0,
  total_ingresos numeric NOT NULL DEFAULT 0,
  total_gastos numeric NOT NULL DEFAULT 0,
  total_ajustes numeric NOT NULL DEFAULT 0,
  saldo_final numeric NOT NULL DEFAULT 0,
  estado text NOT NULL DEFAULT 'CERRADO'::text CHECK (estado = ANY (ARRAY['ABIERTO'::text, 'CERRADO'::text])),
  notas text,
  cerrado_por uuid,
  cerrado_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  saldo_inicial_efectivo numeric NOT NULL DEFAULT 0,
  saldo_inicial_banco numeric NOT NULL DEFAULT 0,
  ingresos_efectivo numeric NOT NULL DEFAULT 0,
  ingresos_banco numeric NOT NULL DEFAULT 0,
  gastos_efectivo numeric NOT NULL DEFAULT 0,
  gastos_banco numeric NOT NULL DEFAULT 0,
  ajustes_efectivo numeric NOT NULL DEFAULT 0,
  ajustes_banco numeric NOT NULL DEFAULT 0,
  saldo_final_efectivo numeric NOT NULL DEFAULT 0,
  saldo_final_banco numeric NOT NULL DEFAULT 0,
  CONSTRAINT cierres_mensuales_pkey PRIMARY KEY (id),
  CONSTRAINT cierres_mensuales_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT cierres_mensuales_cerrado_por_fkey FOREIGN KEY (cerrado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.movimientos_caja (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  anio integer NOT NULL,
  mes integer NOT NULL CHECK (mes >= 1 AND mes <= 12),
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['APORTE'::text, 'RETIRO'::text])),
  monto numeric NOT NULL CHECK (monto > 0::numeric),
  descripcion text,
  fecha timestamp with time zone DEFAULT now(),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  forma_pago text NOT NULL DEFAULT 'efectivo'::text CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'banco'::text])),
  CONSTRAINT movimientos_caja_pkey PRIMARY KEY (id),
  CONSTRAINT movimientos_caja_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT movimientos_caja_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.control_sustancias_dispensacion (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  item_venta_id uuid,
  producto_id uuid NOT NULL,
  paciente_nombre text NOT NULL,
  paciente_documento text NOT NULL,
  medico_nombre text NOT NULL,
  medico_registro_profesional text NOT NULL,
  numero_formula text,
  cantidad_dispensada integer NOT NULL CHECK (cantidad_dispensada > 0),
  fecha_dispensacion timestamp with time zone NOT NULL DEFAULT now(),
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT control_sustancias_dispensacion_pkey PRIMARY KEY (id),
  CONSTRAINT control_sustancias_dispensacion_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT control_sustancias_dispensacion_item_venta_id_fkey FOREIGN KEY (item_venta_id) REFERENCES public.sale_items(id),
  CONSTRAINT control_sustancias_dispensacion_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.products(id),
  CONSTRAINT control_sustancias_dispensacion_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.control_cadena_frio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  fecha_hora timestamp with time zone NOT NULL DEFAULT now(),
  temperatura_c numeric NOT NULL,
  dentro_de_rango boolean NOT NULL DEFAULT true,
  responsable uuid,
  observaciones text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT control_cadena_frio_pkey PRIMARY KEY (id),
  CONSTRAINT control_cadena_frio_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT control_cadena_frio_responsable_fkey FOREIGN KEY (responsable) REFERENCES auth.users(id)
);
CREATE TABLE public.devoluciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  venta_id uuid NOT NULL,
  cliente_id uuid,
  tipo text NOT NULL DEFAULT 'devolucion'::text CHECK (tipo = ANY (ARRAY['devolucion'::text, 'garantia'::text])),
  estado text NOT NULL DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])),
  motivo text NOT NULL,
  monto_total numeric NOT NULL DEFAULT 0,
  reintegra_inventario boolean NOT NULL DEFAULT true,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  resuelto_por uuid,
  resuelto_en timestamp with time zone,
  CONSTRAINT devoluciones_pkey PRIMARY KEY (id),
  CONSTRAINT devoluciones_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT devoluciones_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES public.sales(id),
  CONSTRAINT devoluciones_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clients(id),
  CONSTRAINT devoluciones_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id),
  CONSTRAINT devoluciones_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES auth.users(id)
);
CREATE TABLE public.devolucion_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  devolucion_id uuid NOT NULL,
  empresa_id uuid NOT NULL,
  item_venta_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  lote_id uuid,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  precio_unitario numeric NOT NULL,
  subtotal numeric NOT NULL,
  motivo_item text,
  CONSTRAINT devolucion_items_pkey PRIMARY KEY (id),
  CONSTRAINT devolucion_items_devolucion_id_fkey FOREIGN KEY (devolucion_id) REFERENCES public.devoluciones(id),
  CONSTRAINT devolucion_items_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT devolucion_items_item_venta_id_fkey FOREIGN KEY (item_venta_id) REFERENCES public.sale_items(id),
  CONSTRAINT devolucion_items_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.products(id),
  CONSTRAINT devolucion_items_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.purchase_batches(id)
);
CREATE TABLE public.notas_credito (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  venta_id uuid NOT NULL,
  devolucion_id uuid,
  consecutivo_interno integer,
  concepto text NOT NULL,
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notas_credito_pkey PRIMARY KEY (id),
  CONSTRAINT notas_credito_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT notas_credito_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES public.sales(id),
  CONSTRAINT notas_credito_devolucion_id_fkey FOREIGN KEY (devolucion_id) REFERENCES public.devoluciones(id),
  CONSTRAINT notas_credito_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.notas_debito (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  venta_id uuid,
  cliente_id uuid,
  consecutivo_interno integer,
  concepto text NOT NULL,
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notas_debito_pkey PRIMARY KEY (id),
  CONSTRAINT notas_debito_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT notas_debito_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES public.sales(id),
  CONSTRAINT notas_debito_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clients(id),
  CONSTRAINT notas_debito_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.deudas_proveedor (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  proveedor_id uuid NOT NULL,
  lote_id uuid,
  monto_original numeric NOT NULL CHECK (monto_original > 0::numeric),
  monto_pagado numeric NOT NULL DEFAULT 0 CHECK (monto_pagado >= 0::numeric),
  monto_pendiente numeric DEFAULT (monto_original - monto_pagado),
  estado text NOT NULL DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'parcial'::text, 'pagada'::text, 'cancelada'::text])),
  fecha_vencimiento date,
  notas text,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deudas_proveedor_pkey PRIMARY KEY (id),
  CONSTRAINT deudas_proveedor_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT deudas_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.suppliers(id),
  CONSTRAINT deudas_proveedor_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.purchase_batches(id),
  CONSTRAINT deudas_proveedor_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.pagos_deuda_proveedor (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deuda_id uuid NOT NULL,
  empresa_id uuid NOT NULL,
  monto numeric NOT NULL CHECK (monto > 0::numeric),
  forma_pago text NOT NULL DEFAULT 'efectivo'::text CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'banco'::text])),
  notas text,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pagos_deuda_proveedor_pkey PRIMARY KEY (id),
  CONSTRAINT pagos_deuda_proveedor_deuda_id_fkey FOREIGN KEY (deuda_id) REFERENCES public.deudas_proveedor(id),
  CONSTRAINT pagos_deuda_proveedor_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT pagos_deuda_proveedor_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.ordenes_compra (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  proveedor_id uuid NOT NULL,
  estado text NOT NULL DEFAULT 'borrador'::text CHECK (estado = ANY (ARRAY['borrador'::text, 'enviada'::text, 'recibida_parcial'::text, 'recibida_total'::text, 'cancelada'::text])),
  fecha_esperada date,
  notas text,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ordenes_compra_pkey PRIMARY KEY (id),
  CONSTRAINT ordenes_compra_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT ordenes_compra_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.suppliers(id),
  CONSTRAINT ordenes_compra_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.orden_compra_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  orden_compra_id uuid NOT NULL,
  empresa_id uuid NOT NULL,
  producto_id uuid NOT NULL,
  cantidad_solicitada integer NOT NULL CHECK (cantidad_solicitada > 0),
  cantidad_recibida integer NOT NULL DEFAULT 0 CHECK (cantidad_recibida >= 0),
  costo_unitario_estimado numeric,
  lote_id uuid,
  CONSTRAINT orden_compra_items_pkey PRIMARY KEY (id),
  CONSTRAINT orden_compra_items_orden_compra_id_fkey FOREIGN KEY (orden_compra_id) REFERENCES public.ordenes_compra(id),
  CONSTRAINT orden_compra_items_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT orden_compra_items_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES public.products(id),
  CONSTRAINT orden_compra_items_lote_id_fkey FOREIGN KEY (lote_id) REFERENCES public.purchase_batches(id)
);
CREATE TABLE public.comisiones_devengadas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  venta_id uuid NOT NULL,
  item_venta_id uuid NOT NULL,
  vendedor_id uuid NOT NULL,
  porcentaje_aplicado numeric NOT NULL,
  base_calculo numeric NOT NULL,
  valor_comision numeric NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'pagada'::text, 'anulada'::text])),
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  pagada_en timestamp with time zone,
  CONSTRAINT comisiones_devengadas_pkey PRIMARY KEY (id),
  CONSTRAINT comisiones_devengadas_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT comisiones_devengadas_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES public.sales(id),
  CONSTRAINT comisiones_devengadas_item_venta_id_fkey FOREIGN KEY (item_venta_id) REFERENCES public.sale_items(id),
  CONSTRAINT comisiones_devengadas_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.cajas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  nombre text NOT NULL CHECK (char_length(TRIM(BOTH FROM nombre)) >= 1),
  activa boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cajas_pkey PRIMARY KEY (id),
  CONSTRAINT cajas_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id)
);
CREATE TABLE public.turnos_caja (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  caja_id uuid NOT NULL,
  cajero_id uuid NOT NULL,
  saldo_apertura numeric NOT NULL DEFAULT 0,
  saldo_cierre_esperado numeric,
  saldo_cierre_contado numeric,
  diferencia numeric,
  estado text NOT NULL DEFAULT 'abierto'::text CHECK (estado = ANY (ARRAY['abierto'::text, 'cerrado'::text])),
  abierto_en timestamp with time zone NOT NULL DEFAULT now(),
  cerrado_en timestamp with time zone,
  notas text,
  CONSTRAINT turnos_caja_pkey PRIMARY KEY (id),
  CONSTRAINT turnos_caja_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT turnos_caja_caja_id_fkey FOREIGN KEY (caja_id) REFERENCES public.cajas(id),
  CONSTRAINT turnos_caja_cajero_id_fkey FOREIGN KEY (cajero_id) REFERENCES auth.users(id)
);
CREATE TABLE public.recogidas_efectivo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  turno_id uuid NOT NULL,
  monto numeric NOT NULL CHECK (monto > 0::numeric),
  recogido_por uuid,
  entregado_a text,
  notas text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recogidas_efectivo_pkey PRIMARY KEY (id),
  CONSTRAINT recogidas_efectivo_recogido_por_fkey FOREIGN KEY (recogido_por) REFERENCES auth.users(id),
  CONSTRAINT recogidas_efectivo_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT recogidas_efectivo_turno_id_fkey FOREIGN KEY (turno_id) REFERENCES public.turnos_caja(id)
);
CREATE TABLE public.deudas_cajero (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  turno_id uuid NOT NULL,
  cajero_id uuid NOT NULL,
  monto_original numeric NOT NULL CHECK (monto_original > 0::numeric),
  monto_pagado numeric NOT NULL DEFAULT 0 CHECK (monto_pagado >= 0::numeric),
  monto_pendiente numeric DEFAULT (monto_original - monto_pagado),
  estado text NOT NULL DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'parcial'::text, 'pagada'::text, 'cancelada'::text])),
  notas text,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deudas_cajero_pkey PRIMARY KEY (id),
  CONSTRAINT deudas_cajero_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT deudas_cajero_turno_id_fkey FOREIGN KEY (turno_id) REFERENCES public.turnos_caja(id),
  CONSTRAINT deudas_cajero_cajero_id_fkey FOREIGN KEY (cajero_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pagos_deuda_cajero (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deuda_id uuid NOT NULL,
  empresa_id uuid NOT NULL,
  monto numeric NOT NULL CHECK (monto > 0::numeric),
  forma_pago text NOT NULL DEFAULT 'efectivo'::text CHECK (forma_pago = ANY (ARRAY['efectivo'::text, 'banco'::text])),
  notas text,
  creado_por uuid,
  creado_en timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pagos_deuda_cajero_pkey PRIMARY KEY (id),
  CONSTRAINT pagos_deuda_cajero_deuda_id_fkey FOREIGN KEY (deuda_id) REFERENCES public.deudas_cajero(id),
  CONSTRAINT pagos_deuda_cajero_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.companies(id),
  CONSTRAINT pagos_deuda_cajero_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id)
);